---
- name: Установка Docker, Docker  Compose, Node Exporter,
  hosts: all
  become: true
  become_method: sudo
  vars:
    prereq_pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - mc
      - htop
      # - ntopng
      - traceroute
      - ncdu
      - iftop
      - jq
      - tcpdump
      - iotop
      - wget
      - rsync
      - vim
      - parted
      - gnupg
      - sysstat

  tasks:

    - name: Установим пакеты необходимые для установки Docker
      apt:
        update_cache: yes
        pkg: "{{prereq_pkg}}"
        state: present

    - name: Скачаем и добавим GPG ключ репозитория Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавим официальный репозиторий Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Обновим кэш apt и установим Docker
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Установим python библиотеку для работы с Docker Engine API
      pip:
        name: docker
        state: present
      ignore_errors: yes

    - name: Установим Docker Compose
      pip:
        name: docker-compose
        state: present
      ignore_errors: yes

    - name: Скачаем node exporter с GitHub
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /tmp

    - name: Разархивируем node exporter
      unarchive:
        remote_src: yes
        src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /tmp

    - name: Создадим пользователя node_exporter
      user:
        name: node_exporter
        comment: node_exporter
        system: true
        create_home: false

    - name: Перемещаем разархивированный node exporter в /usr/local/bin
      copy:
        src: /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        remote_src: yes
        owner: node_exporter
        group: node_exporter
        mode: 0755

    - name: Создадим systemd unit файл
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0600

    - name: Запустим созданный сервис node exporter
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: node_exporter.service

    - name: Создадим рабочую директорию для Docker Compose, Prometheus, Grafana
      file:
        path: /opt/prometheus
        state: directory

    - name: Создадим Docker Compose файл из шаблона
      template:
        src: docker_compose.j2
        dest: /opt/prometheus/docker-compose.yml

    - name: Создадим файл настроек Prometheus из шаблона
      template:
        src: prometheus.j2
        dest: /opt/prometheus/prometheus.yml

    - name: Создадим директорию для првиженинга датасурсов в Grafana
      file:
        path: /opt/prometheus/grafana/provisioning/datasources/
        state: directory

    - name: Создадим файл настроек источника  данных для Grafana из шаблона
      template:
        src: prometheus_datasource.j2
        dest: /opt/prometheus/grafana/provisioning/datasources/prometheus_datasource.yml

    - name: Создадим директорию для првиженинга дашбордов в графане
      file:
        path: /opt/prometheus/grafana/provisioning/dashboards/
        state: directory

    - name: Создадим файл дефолтного дашборда для Grafana из шаблона
      template:
        src: default_dashboard.j2
        dest: /opt/prometheus/grafana/provisioning/dashboards/default_dashboard.yml

    - name: Подсовываем шаблон дашборда 1860 с офф сайта Grafana
      copy:
        src: node-exporter-full_rev30.json
        dest: /opt/prometheus/grafana/provisioning/dashboards/node-exporter-full_rev30.json

    - name: Запустим контейнеры Docker Compose
      docker_compose:
        project_src: /opt/prometheus
        files: docker-compose.yml
